### ISSUE TITLE
Connection easily lost, can't reconnect

### ISSUE THREAD

**Issue by fcassata** [bsharper/atv-desktop-remote#47]
I've had this issue since I start using the program v.1.1.1, now on v1.2

Often when the computer sleeps but stays on the same network I lose connection to the ATV. Same thing happens if I leave the house with the app running, join another network elsewhere, and come back home, the connection is lost.

The only way to restore the connection is to restart the app.

Would love to be able to just keep the app open at all times and be able to reconnect successfully if the connection is dropped and the paired ATV is detected on the network.

**Comment by bsharper** [comment]
Try pressing Cmd+R or Ctrl+R or Ctrl+Shift+R while it's open. This should cause it to refresh and reconnect.

**Comment by bsharper** [comment]
I'll look and see if I can figure out why it's doing that this weekend. There is some existing reconnection code but it's possible the underlying library has some better options for this as well.

**Comment by jklewa** [comment]
@bsharper I've looked into a few causes of this working on my fork.

Here are a few ways the app can get stuck in a "disconnected" state
1. The app doesn't display a connection status/errors
   * Suggestion: Display a message when connection_failure:true [example](https://github.com/jklewa/atv-desktop-remote/blob/d059a9318b22a15e0c14d77c0dc7b565199ec34d/app/web_remote.js#L256)
2. Websocket server can crash but it isn't restarted
   * Suggestion: Detect failed websocket servers and attempt some restarts https://github.com/bsharper/atv-desktop-remote/pull/34
3. Websocket server throws some exceptions while we are "disconnected"
   * Suggestion: Update wwserver.py to handle empty atv.scan() results [example](https://github.com/jklewa/atv-desktop-remote/blob/d059a9318b22a15e0c14d77c0dc7b565199ec34d/server/wsserver.py#L181)

**Comment by fcassata** [comment]
> The app doesn't display a connection status/errors
> 
>     * Suggestion: Display a message when connection_failure:true [example](https://github.com/jklewa/atv-desktop-remote/blob/d059a9318b22a15e0c14d77c0dc7b565199ec34d/app/web_remote.js#L256)

This would go a long way to make it not feel broken when the connection is lost. If the UI showed the connection status (maybe only in the case of no connection), and would either have a button or text with the refresh shortcut.

**Comment by jklewa** [comment]
I did some testing and refactoring to address the connection issues. Most of the changes boil down to this "ConnectionManager" refactor https://github.com/jklewa/atv-desktop-remote/commit/97db530e764f7741b597eee47a8298cc9cd302f1 and combining remote modules https://github.com/jklewa/atv-desktop-remote/commit/ba4edc62d0cb8fd9c76d8ee39183e21d30f4faa9, with the full diff https://github.com/jklewa/atv-desktop-remote/compare/v1.3.0...v1.4.0-pre

Pre-release builds: https://github.com/jklewa/atv-desktop-remote/releases/tag/v1.4.0-pre

@fcassata @bsharper Testing all the different ways a disconnect can happen can be tricky. Are you willing to try this pre-release and let me know if I missed anything?

**Comment by fcassata** [comment]
> [@fcassata](https://github.com/fcassata) [@bsharper](https://github.com/bsharper) Testing all the different ways a disconnect can happen can be tricky. Are you willing to try this pre-release and let me know if I missed anything?

I'm running this build now, I'll report back tomorrow after I come back home from work, that's the most reliable way to lose the connection for me...

The ? for the shortcuts and power buttons are nice additions!

**Comment by fcassata** [comment]
@bsharper @jklewa the only way I've always lost connection and had to refresh to reconnect is when I get home from work, it has never once worked without a reconnect. It's fine now, it reconnected successfully. So for me it looks like this is fixed!

Just a quick comment, don't know if it's pre-release related but I was a bigger fan of having the remote drop down from the menubar than having it free floating. Also the free floating one has a super thin top grab bar to move it around, would be better UX to skip it altogether and have the window draggable on all empty space, that is if the free floating thing is here to stay :)

**Comment by jklewa** [comment]
@fcassata Thanks for the additional feedback!

To be clear, that fix is in a **fork** ([jklewa/atv-desktop-remote](https://github.com/jklewa/atv-desktop-remote)), so it's not yet fixed in [bsharper/atv-desktop-remote](https://github.com/bsharper/atv-desktop-remote), though I'm happy to work with @bsharper to implement the same fixes.

**Comment by fcassata** [comment]
> [@fcassata](https://github.com/fcassata) Thanks for the additional feedback!
> 
> To be clear, that fix is in a **fork** ([jklewa/atv-desktop-remote](https://github.com/jklewa/atv-desktop-remote)), so it's not yet fixed in [bsharper/atv-desktop-remote](https://github.com/bsharper/atv-desktop-remote), though I'm happy to work with [@bsharper](https://github.com/bsharper) to implement the same fixes.

Gotcha, thanks!
